Failure # 1 (occurred at 2025-01-27_12-57-52)
[36mray::ImplicitFunc.train()[39m (pid=41628, ip=10.12.92.124, actor_id=8b804f3afc59020768410d3601000000, repr=ray_tune_trainable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
             ^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/parallel_exec_2.py", line 232, in ray_tune_trainable
    master_config = config.load_config()
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'load_config'
