Failure # 1 (occurred at 2025-01-24_11-25-07)
[36mray::ImplicitFunc.train()[39m (pid=319149, ip=10.12.92.124, actor_id=84c5ae8d148d11477196ed5001000000, repr=ray_tune_trainable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 375, in train
    raise skipped from exception_cause(skipped)
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 349, in entrypoint
    return self._trainable_func(
           ^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/envOWHP/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 666, in _trainable_func
    output = fn()
             ^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/parallel_exec.py", line 247, in ray_tune_trainable
    train.main(config_dict=master_config,
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/train.py", line 856, in main
    learner = Learner(tensorboard_tracker=tracker,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scs_deal_learning/users/mchowdhu/OptimisingWeightUpdateHyperparameters/train.py", line 97, in __init__
    self.config_dicts['model']['class'])(
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'model'
