Failure # 1 (occurred at 2025-01-24_10-07-24)
Traceback (most recent call last):
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TuneError): [36mray::ImplicitFunc.train_buffered()[39m (pid=15140, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000222E5489970>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\trainable.py", line 224, in train_buffered
    result = self.train()
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\trainable.py", line 283, in train
    result = self.step()
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\function_runner.py", line 381, in step
    self._report_thread_runner_error(block=True)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\function_runner.py", line 528, in _report_thread_runner_error
    raise TuneError(
ray.tune.error.TuneError: Trial raised an exception. Traceback:
[36mray::ImplicitFunc.train_buffered()[39m (pid=15140, ip=127.0.0.1, repr=<types.ImplicitFunc object at 0x00000222E5489970>)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\function_runner.py", line 262, in run
    self._entrypoint()
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\function_runner.py", line 330, in entrypoint
    return self._trainable_func(self.config, self._status_reporter,
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\envOWUH\lib\site-packages\ray\tune\function_runner.py", line 599, in _trainable_func
    output = fn()
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\parallel_exec.py", line 247, in ray_tune_trainable
    train.main(config_dict=master_config,
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\train.py", line 856, in main
    learner = Learner(tensorboard_tracker=tracker,
  File "F:\Fraunhofer\Mini AutoML Project\SOTA\Optimising Weight Update Hyperparameters\OptimisingWeightUpdateHyperparameters\train.py", line 97, in __init__
    self.config_dicts['model']['class'])(
KeyError: 'model'

